# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
            - name: Veracode Profile Sandboxes Helper
  # You may pin to the exact commit or the version.
  # uses: veracode/veracode-sandboxes-helper@baa0a8458605b92d261b6b8f7801fa67fdce501b
  uses: veracode/veracode-sandboxes-helper@v1.0.0
  with:
    # The activity expected from the Action: clean, promote-latest-scan, remove-sandbox
    activity: # optional
    # Veracode Application name
    app-name: 
    # Sandbox name for actions related to a specific Sandbox
    sandbox-name: # optional
    # The amount of oldest scanned-in sandboxes to remove
    clean-amount: # optional, default is 1
    # Deletes the sandbox after its promotion. Only works with the [promote] activity. Default is false
    delete-on-promote: # optional, default is false
    # The number of days which the sandbox had no activity
    clean-modified-before: # optional, default is 0
                      - name: Azure Resource Manager (ARM) Template Deployment
  # You may pin to the exact commit or the version.
  # uses: whiteducksoftware/azure-arm-action@9bae2e95df87dbd4acae11deb0765be7256fd141
  uses: whiteducksoftware/azure-arm-action@v3.3
  with:
    # Paste output of `az ad sp create-for-rbac -o json` as value of secret variable: AZURE_CREDENTIALS
    creds: 
    # Provide the name of a resource group.
    resourceGroupName: 
    # Specify the path to the Azure Resource Manager template.
    templateLocation: 
    # Specifies the name of the resource group deployment to create.
    deploymentName: 
    # Incremental (only add resources to resource group) or Complete (remove extra resources from resource group).
    deploymentMode: # optional, default is Incremental
    # Specify either path to the Azure Resource Manager parameters file or pass them as 'key1=value1;key2=value2;...'.
    parameters: # optional
    # Specify either path to the Azure Resource Manager override parameters file or pass them as 'key1=value1;key2=value2;...'.
    overrideParameters: # optional
                      - name: Azure Resource Manager (ARM) Template Deployment
  # You may pin to the exact commit or the version.
  # uses: whiteducksoftware/azure-arm-action@9bae2e95df87dbd4acae11deb0765be7256fd141
  uses: whiteducksoftware/azure-arm-action@v3.3
  with:
    # Paste output of `az ad sp create-for-rbac -o json` as value of secret variable: AZURE_CREDENTIALS
    creds: 
    # Provide the name of a resource group.
    resourceGroupName: 
    # Specify the path to the Azure Resource Manager template.
    templateLocation: 
    # Specifies the name of the resource group deployment to create.
    deploymentName: 
    # Incremental (only add resources to resource group) or Complete (remove extra resources from resource group).
    deploymentMode: # optional, default is Incremental
    # Specify either path to the Azure Resource Manager parameters file or pass them as 'key1=value1;key2=value2;...'.
    parameters: # optional
    # Specify either path to the Azure Resource Manager override parameters file or pass them as 'key1=value1;key2=value2;...'.
    overrideParameters: # optional
                - name: Upwind Create Image Build Event
  # You may pin to the exact commit or the version.
  # uses: upwindsecurity/create-image-build-event-action@1d91a4ecb87b1581ca86e8fe8af999dd87586dbb
  uses: upwindsecurity/create-image-build-event-action@v2
  with:
    # The execution mode of the action. Setting it to `'true'` simulates event creation without executing it.
    dry_run: # optional, default is false
    # The image associated with the build event.
    image: 
    # The image SHA associated with the build event.
    image_sha: 
    # The Management API endpoint.
    upwind_api_endpoint: # optional, default is https://api.upwind.io
    # The Authentication API endpoint.
    upwind_auth_endpoint: # optional, default is https://auth.upwind.io
    # The client ID used for authentication with the Upwind Authorization Service.
    upwind_client_id: 
    # The client secret for authentication with the Upwind Authorization Service.
    upwind_client_secret: 
    # The identifier of the Upwind organization associated with the event.
    upwind_organization_id: 

                      - name: Upwind Create Image Build Event
  # You may pin to the exact commit or the version.
  # uses: upwindsecurity/create-image-build-event-action@1d91a4ecb87b1581ca86e8fe8af999dd87586dbb
  uses: upwindsecurity/create-image-build-event-action@v2
  with:
    # The execution mode of the action. Setting it to `'true'` simulates event creation without executing it.
    dry_run: # optional, default is false
    # The image associated with the build event.
    image: 
    # The image SHA associated with the build event.
    image_sha: 
    # The Management API endpoint.
    upwind_api_endpoint: # optional, default is https://api.upwind.io
    # The Authentication API endpoint.
    upwind_auth_endpoint: # optional, default is https://auth.upwind.io
    # The client ID used for authentication with the Upwind Authorization Service.
    upwind_client_id: 
    # The client secret for authentication with the Upwind Authorization Service.
    upwind_client_secret: 
    # The identifier of the Upwind organization associated with the event.
    upwind_organization_id: 
          
          
